/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: XT2I4NujKv2lE+O9J526Kh8sfvR/Gq1qatLlQAZ+6tORFDzPbxUWAztPq9DMDafV/acmuYCuTaVS4gAAZBODGA==
 */

/* eslint-disable */
// tslint:disable

interface Leases {
  chainId: (string) | null
  createdAt: (string | Date)
  depositAmount: unknown
  /**
   * @default 0
   */
  depositCalculated: (boolean | number)
  endDate: (string | Date)
  /**
   * @default generic
   */
  endType: ("generic" | "switchRoom" | "switchHouse" | "moveout" | "extend")
  extensionAccepted: ((boolean | number)) | null
  /**
   * @default 0
   */
  hasCompletedOnboarding: (boolean | number)
  /**
   * @default 0
   */
  hasLateFees: (boolean | number)
  /**
   * @default 0
   */
  hasMovedIn: (boolean | number)
  /**
   * @default 0
   */
  hasMovedOut: (boolean | number)
  hubId: string
  id: string & {readonly __brand?: 'leases_id'}
  moveInDate: ((string | Date)) | null
  moveoutDate: (string | Date)
  moveoutDateRequest: ((string | Date)) | null
  moveoutDesiderata: (string) | null
  moveoutReason: (string) | null
  name: string
  number: number
  onboardingCompletedDate: ((string | Date)) | null
  preferredMoveoutDate: ((string | Date)) | null
  rentAmount: unknown
  roomId: (string) | null
  sendgridBatchId: (string) | null
  signatureDate: (string | Date)
  startDate: (string | Date)
  /**
   * @default generic
   */
  startType: ("generic" | "switchRoom" | "switchHouse" | "moveout" | "extend")
  /**
   * @default signed
   */
  status: ("signed" | "void" | "active" | "cancelled" | "finished")
  stripeSubscriptionId: (string) | null
  updatedAt: (string | Date)
  userId: (string) | null
}
export default Leases;

interface Leases_InsertParameters {
  chainId?: (string) | null
  createdAt: (string | Date)
  depositAmount: unknown
  /**
   * @default 0
   */
  depositCalculated?: (boolean | number)
  endDate: (string | Date)
  /**
   * @default generic
   */
  endType?: ("generic" | "switchRoom" | "switchHouse" | "moveout" | "extend")
  extensionAccepted?: ((boolean | number)) | null
  /**
   * @default 0
   */
  hasCompletedOnboarding?: (boolean | number)
  /**
   * @default 0
   */
  hasLateFees?: (boolean | number)
  /**
   * @default 0
   */
  hasMovedIn?: (boolean | number)
  /**
   * @default 0
   */
  hasMovedOut?: (boolean | number)
  hubId: string
  id: string & {readonly __brand?: 'leases_id'}
  moveInDate?: ((string | Date)) | null
  moveoutDate: (string | Date)
  moveoutDateRequest?: ((string | Date)) | null
  moveoutDesiderata?: (string) | null
  moveoutReason?: (string) | null
  name: string
  number: number
  onboardingCompletedDate?: ((string | Date)) | null
  preferredMoveoutDate?: ((string | Date)) | null
  rentAmount: unknown
  roomId?: (string) | null
  sendgridBatchId?: (string) | null
  signatureDate: (string | Date)
  startDate: (string | Date)
  /**
   * @default generic
   */
  startType?: ("generic" | "switchRoom" | "switchHouse" | "moveout" | "extend")
  /**
   * @default signed
   */
  status?: ("signed" | "void" | "active" | "cancelled" | "finished")
  stripeSubscriptionId?: (string) | null
  updatedAt: (string | Date)
  userId?: (string) | null
}
export type {Leases_InsertParameters}
