/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ML20u931WjUv6uMEoCQ3Rp841vf7+2YQH24FAhGLovVYbtA7oIUyXDdQreZiKiEsxcLanHAPsGllalbq80DP8g==
 */

/* eslint-disable */
// tslint:disable

import Houses, {Houses_InsertParameters} from './houses'
import Leases, {Leases_InsertParameters} from './leases'
import Payments, {Payments_InsertParameters} from './payments'

interface DatabaseSchema {
  houses: {record: Houses, insert: Houses_InsertParameters};
  leases: {record: Leases, insert: Leases_InsertParameters};
  payments: {record: Payments, insert: Payments_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}
