/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: VfkMymyjtmnhTg/VA17os6xJmHpwqQxCkwjld1Pctdg19KIpzMG6P7mi6hkSHcwHDx2v1NDR+0IMfnKh6j2avw==
 */

/* eslint-disable */
// tslint:disable

import Houses, {Houses_InsertParameters} from './houses'
import Leases, {Leases_InsertParameters} from './leases'
import Payments, {Payments_InsertParameters} from './payments'
import Rooms, {Rooms_InsertParameters} from './rooms'
import Users, {Users_InsertParameters} from './users'

interface DatabaseSchema {
  houses: {record: Houses, insert: Houses_InsertParameters};
  leases: {record: Leases, insert: Leases_InsertParameters};
  payments: {record: Payments, insert: Payments_InsertParameters};
  rooms: {record: Rooms, insert: Rooms_InsertParameters};
  users: {record: Users, insert: Users_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}
