/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: O+wzQXc4vxa9+oyywdc4F2UJYxVZOVEtgxN+EmTI0VCsD3D6qIn+eINhhNDsMau4L991GpKrsAUi7SBQQ68H/w==
 */

/* eslint-disable */
// tslint:disable

import Leases, {Leases_InsertParameters} from './leases'
import Rooms, {Rooms_InsertParameters} from './rooms'
import Users, {Users_InsertParameters} from './users'

interface DatabaseSchema {
  leases: {record: Leases, insert: Leases_InsertParameters};
  rooms: {record: Rooms, insert: Rooms_InsertParameters};
  users: {record: Users, insert: Users_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}
