/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: LTlDiIDYgtp9n46D4sZ60Rug70CdysVHBmrG+/lmh7G30gAh4s4NnBR8cgTbYyGyFBBqGG7QU+liyprRKqbb7Q==
 */

/* eslint-disable */
// tslint:disable

interface Rooms {
  /**
   * @default 1
   */
  active: (boolean | number)
  baseRent: (unknown) | null
  category: (("essential" | "essentialPlus" | "classic" | "classicPlus" | "affinity" | "affinityPlus" | "solidarity" | "PMR")) | null
  cmsId: (number) | null
  createdAt: (string | Date)
  /**
   * @default 0
   */
  deleted: (boolean | number)
  deposit: (unknown) | null
  description: (string) | null
  houseId: (string) | null
  id: string & {readonly __brand?: 'rooms_id'}
  location: (string) | null
  lockId: (string) | null
  number: (number) | null
  rent: (unknown) | null
  stripeProductId: (string) | null
  surface: (number) | null
  unitId: (string) | null
  updatedAt: (string | Date)
}
export default Rooms;

interface Rooms_InsertParameters {
  /**
   * @default 1
   */
  active?: (boolean | number)
  baseRent?: (unknown) | null
  category?: (("essential" | "essentialPlus" | "classic" | "classicPlus" | "affinity" | "affinityPlus" | "solidarity" | "PMR")) | null
  cmsId?: (number) | null
  createdAt: (string | Date)
  /**
   * @default 0
   */
  deleted?: (boolean | number)
  deposit?: (unknown) | null
  description?: (string) | null
  houseId?: (string) | null
  id: string & {readonly __brand?: 'rooms_id'}
  location?: (string) | null
  lockId?: (string) | null
  number?: (number) | null
  rent?: (unknown) | null
  stripeProductId?: (string) | null
  surface?: (number) | null
  unitId?: (string) | null
  updatedAt: (string | Date)
}
export type {Rooms_InsertParameters}
