/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: vvYlc8s0T9W/mgQs8KU6JMCujS7KeTDaWSkRNPxWygBhRO7OlV9DWw9O7CEbDvVrYPjrJ9nafPJEQx+6v4eGPA==
 */

/* eslint-disable */
// tslint:disable

interface Users {
  about: (string) | null
  /**
   * @default 1
   */
  active: (boolean | number)
  address: (string) | null
  /**
   * @default 0
   */
  alreadyConnected: (boolean | number)
  /**
   * @default 1
   */
  autoRefundDeposit: (boolean | number)
  /**
   * @default 0
   */
  banned: (boolean | number)
  bio: (string) | null
  birthdate: ((string | Date)) | null
  /**
   * @default 1
   */
  birthdateVisibility: (boolean | number)
  /**
   * @default 0
   */
  confirmed: (boolean | number)
  createdAt: (string | Date)
  email: string
  /**
   * @default 1
   */
  emailVisibility: (boolean | number)
  employment: (("employed" | "unemployed" | "self-employed" | "student")) | null
  facebook: (string) | null
  firstName: (string) | null
  gender: (("male" | "female" | "other")) | null
  /**
   * @default 1
   */
  genderVisibility: (boolean | number)
  id: string & {readonly __brand?: 'users_id'}
  instagram: (string) | null
  interests: (string) | null
  job: (string) | null
  lastName: (string) | null
  linkedIn: (string) | null
  nationalityId: (string) | null
  nickName: (string) | null
  password: (string) | null
  phoneNumber: (string) | null
  /**
   * @default 1
   */
  phoneNumberVisibility: (boolean | number)
  picture: (string) | null
  prefixId: (string) | null
  residency: (string) | null
  role: (("admin" | "communityManager" | "hubManager" | "propertyManager" | "intern" | "cleaning" | "user")) | null
  salt: (string) | null
  /**
   * @default 0
   */
  serviceVouchers: (boolean | number)
  stripeCustomerId: (string) | null
  twitter: (string) | null
  updatedAt: (string | Date)
  zendeskId: ((string | number | BigInt)) | null
}
export default Users;

interface Users_InsertParameters {
  about?: (string) | null
  /**
   * @default 1
   */
  active?: (boolean | number)
  address?: (string) | null
  /**
   * @default 0
   */
  alreadyConnected?: (boolean | number)
  /**
   * @default 1
   */
  autoRefundDeposit?: (boolean | number)
  /**
   * @default 0
   */
  banned?: (boolean | number)
  bio?: (string) | null
  birthdate?: ((string | Date)) | null
  /**
   * @default 1
   */
  birthdateVisibility?: (boolean | number)
  /**
   * @default 0
   */
  confirmed?: (boolean | number)
  createdAt: (string | Date)
  email: string
  /**
   * @default 1
   */
  emailVisibility?: (boolean | number)
  employment?: (("employed" | "unemployed" | "self-employed" | "student")) | null
  facebook?: (string) | null
  firstName?: (string) | null
  gender?: (("male" | "female" | "other")) | null
  /**
   * @default 1
   */
  genderVisibility?: (boolean | number)
  id: string & {readonly __brand?: 'users_id'}
  instagram?: (string) | null
  interests?: (string) | null
  job?: (string) | null
  lastName?: (string) | null
  linkedIn?: (string) | null
  nationalityId?: (string) | null
  nickName?: (string) | null
  password?: (string) | null
  phoneNumber?: (string) | null
  /**
   * @default 1
   */
  phoneNumberVisibility?: (boolean | number)
  picture?: (string) | null
  prefixId?: (string) | null
  residency?: (string) | null
  role?: (("admin" | "communityManager" | "hubManager" | "propertyManager" | "intern" | "cleaning" | "user")) | null
  salt?: (string) | null
  /**
   * @default 0
   */
  serviceVouchers?: (boolean | number)
  stripeCustomerId?: (string) | null
  twitter?: (string) | null
  updatedAt: (string | Date)
  zendeskId?: ((string | number | BigInt)) | null
}
export type {Users_InsertParameters}
